from __future__ import annotations

import re
from typing import Any

from backend.agents.base import BaseAgent


class AIAuthorshipAgent(BaseAgent):
    name = "ai_authorship"
    description = "AI yazarlik riski icin notu etkilemeyen uyari ajani"

    async def analyze(self, input_data: dict[str, Any]) -> dict[str, Any]:
        source = str(input_data.get("source_code") or "")
        lowered = source.lower()
        signals: list[str] = []
        counter_signals: list[str] = []

        explicit_patterns = [
            "as an ai language model",
            "i will provide the complete",
            "here is the solution",
            "generated by chatgpt",
            "ai-generated",
        ]
        if any(pattern in lowered for pattern in explicit_patterns):
            signals.append("Kod/yorum icinde AI asistan kalibi veya meta aciklama var.")

        comment_lines = [line.strip() for line in source.splitlines() if line.strip().startswith(("#", "//"))]
        if len(comment_lines) >= 4:
            signals.append("Yorum yogunlugu teslim koduna gore yuksek.")

        if re.search(r"\bstep\s*[0-9]+|\badim\s*[0-9]+", lowered):
            signals.append("Cozum anlatimi adim adim uretilmis metin kalibi tasiyor.")

        if re.search(r"\bprint\s*\(|\binput\s*\(", source) and len(source.splitlines()) <= 40:
            counter_signals.append("Kisa ve calistirilabilir ogrenci cozumu izleri var.")
        if re.search(r"\bTODO\b|pass\s*(#|$)", source):
            counter_signals.append("Eksik veya taslak kod izleri otomatik yazarlik kesinligini dusurur.")

        raw_score = len(signals) * 0.35 - len(counter_signals) * 0.15
        if any(pattern in lowered for pattern in explicit_patterns):
            raw_score = max(raw_score, 0.80)
        confidence = max(0.05, min(0.95, raw_score))
        if confidence >= 0.70:
            risk = "high"
        elif confidence >= 0.45:
            risk = "medium"
        elif confidence >= 0.20:
            risk = "low"
        else:
            risk = "safe"

        recommendation = (
            "Notu otomatik dusurme; ogrenciden kisa sozlu aciklama veya commit gecmisi iste."
            if risk in {"medium", "high"}
            else "AI yazarlik icin belirgin kanit yok; yalnizca normal degerlendirme surecini kullan."
        )

        return {
            "risk_level": risk,
            "confidence": round(confidence, 2),
            "signals": signals,
            "counter_signals": counter_signals,
            "recommendation": recommendation,
        }
